name: Konstantinos Passadis Fetch Function Keys and signatures

on:
  workflow_dispatch:
    branches:
    - NoAzureADNoCosmos

env:
  RG: rg_CrewTaskMgr
  FUNCTIONAPP: jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs

jobs:
  configure-apim:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Acquire Azure AD token (bash)
      id: azure-token
      run: |
        token=$(az account get-access-token --query 'accessToken' -o tsv)
        echo "::set-output name=token::$token"
      shell: bash
    
    - name: Use Bearer Token to Make REST Call (Powershell)
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $subscriptionId = (az account show --query 'id' -o tsv)
          $token = "${{ steps.azure-token.outputs.token }}"
          $uri = "https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$env:RG/providers/Microsoft.Web/sites/$env:FUNCTIONAPP/host/default/listKeys?api-version=2018-11-01"
          $functionkeylist = az rest --headers "Authorization=Bearer $token" --method post --uri $uri
          $keylistobject = $functionkeylist | ConvertFrom-Json
          $functionKey = $keylistobject.functionKeys.default
          Write-Output "Function Key: $functionKey"
        azPSVersion: "latest"
