name: Demo Azure REST API in Github Workflow
on:
  workflow_dispatch:
    branches:
    - master

jobs:
  demo-rest-api-call:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        creds: ${{ secrets.AZURE_CLIENT_SECRET }}
        enable-AzPSSession: true

    - name: Make Azure REST API Call
      run: |
        curl -X GET -H "Authorization: Bearer $AZURE_HTTP_API_AUTH_TOKEN" \
        https://management.azure.com/subscriptions/{subscription_id}/resourceGroups?api-version=2021-04-01
