name: Build and deploy .NET Core application to Function App jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs
on:
  workflow_dispatch:
    branches:
    - master
env:
  AZURE_FUNCTIONAPP_NAME: jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs
  AZURE_FUNCTIONAPP_PACKAGE_PATH: .\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: .
  RG: rg_CrewTaskMgr
  functionApp: jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs

jobs:
  configure-apim:
    runs-on: windows-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}    
    - name: get-accessToken
      run: |
          Uninstall-AzureRm
          Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
          Import-Module Az
          Connect-AzAccount
          $accountInfo = az account show
          $accountInfoObject = $accountInfo | ConvertFrom-Json
          $subscription  = $accountInfoObject.id
          $token = (Get-AzAccessToken -ResourceUrl https://management.azure.com).Token
          $functionName = "jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs"
          $uri = "https://management.azure.com/subscriptions/$subscription/resourceGroups/$ENV:RG/providers/Microsoft.Web/sites/$ENV:functionApp/functions/$functionName/listkeys?api-version=2015-08-01"
          $functionKeys = Invoke-RestMethod -Method Post -Uri $uri -Headers @{ Authorization = "Bearer $accessToken" }
  
