name: Build and deploy .NET Core application to Function App jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs
on:
  workflow_dispatch:
    branches:
    - master
  push:
    branches:
    - master
env:
  AZURE_FUNCTIONAPP_NAME: jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs
  AZURE_FUNCTIONAPP_PACKAGE_PATH: .\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: .
  RG: rg_CrewTaskMgr
  FUNCTIONAPP:  jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs
  FUNCTIONNAME: jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs


jobs:
  configure-apim:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Acquire Azure AD token (bash)
      id: azure-token
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
      shell: bash
      run: |
        export AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
        export AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
        export AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
        az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
        echo "Bearer $(az account get-access-token --query 'accessToken' -o tsv)" >> token.txt
        echo "::set-output name=token::$(cat token.txt)"
    
    - name: Use Bearer Token to Make REST Call (Bash)
      shell: pwsh
      run: |
        $accountInfo=az account show
        $accountInfoObject=$accountInfo | ConvertFrom-Json
        $subscriptionId=$accountInfoObject.id
        write-output "subscription=$subscriptionId"
        $token=$(cat token.txt)
        # Use the $token variable in your REST call
        # For example, to call an Azure API, you might use curl or Invoke-RestMethod
        $functionkeylist=az rest --headers "Authorization=Bearer $token" --method post --uri "https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$RG/providers/Microsoft.Web/sites/$FUNCTIONNAME/host/default/listKeys?api-version=2018-11-01"
        $keylistobject=$functionkeylist | ConvertFrom-Json
        $functionKey=$keylistobject.functionKeys.default

  
