name: Konstantinos Passadis Fetch Function Keys and signatures from Function App

on:
  workflow_dispatch:
    branches:
    - master
    - NoAzureADNoCosmos
  push:
    branches:
    - NoAzureADNoCosmos

env:
  AZURE_FUNCTIONAPP_NAME: jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs
  FUNCTIONAPP: jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs
  AZURE_FUNCTIONAPP_PACKAGE_PATH: .\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: .
  RG: rg_CrewTaskMgr

jobs:
  demo-rest-api-call:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        creds: ${{ secrets.AZURE_CLIENT_SECRET }}
        enable-AzPSSession: true

    - name: Acquire Azure AD token (bash)
      id: azure-token
      shell: bash
      run: |
        token=$(az account get-access-token --query 'accessToken' -o tsv)
        echo "::set-output name=token::$token"

    - name: Make Azure REST API Call
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $subscriptionId = (az account show --query 'id' -o tsv)
          $token = "${{ steps.azure-token.outputs.token }}"
          $uri = "https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$env:RG/providers/Microsoft.Web/sites/$env:FUNCTIONAPP/host/default/listKeys?api-version=2018-11-01"
          $functionkeylist = az rest --headers "Authorization=Bearer $token" --method post --uri $uri
          $keylistobject = $functionkeylist | ConvertFrom-Json
          $functionKey = $keylistobject.functionKeys.default
          Write-Output "Function Key: $functionKey"
        azPSVersion: "latest"
