name: Rebuild Azure API Mgr and add Azure Functions

on:
  workflow_dispatch:
    branches:
    - master

  push:
    branches:
    - master

env:
  AZURE_FUNCTIONAPP_NAME: jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs
  FUNCTIONAPP: jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs
  AZURE_FUNCTIONAPP_PACKAGE_PATH: .\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: .
  RG: rg_CrewTaskMgr
  LOC: westus
  UNIQUE_NAME: jac3sukjdrxzi

jobs:
  demo-rest-api-call:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        creds: ${{ secrets.AZURE_CLIENT_SECRET }}
        enable-AzPSSession: true

    - name: Make Azure REST API Call
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $AZURE_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"
          $AZURE_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"
          $AZURE_TENANT_ID="${{ secrets.AZURE_TENANT_ID }}"
          az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
          $subscriptionId = (az account show --query 'id' -o tsv)
          write-output "list apims"
          az apim list  --resource-group $env:RG
          $APIM_SERVICE_NAME= "$env:UNIQUE_NAME-apim"
          write-output "delete $APIM_SERVICE_NAME"
          az apim delete --name $APIM_SERVICE_NAME --resource-group $env:RG --yes
          write-output "purge $APIM_SERVICE_NAME"
          az apim deletedservice purge --service-name $APIM_SERVICE_NAME --location $env:LOC
          $API_ID="$env:UNIQUE_NAME-APIM-CrewTaskMgrAuthSvcs"
          write-output "API_ID=$API_ID APIM_SERVICE_NAME=$APIM_SERVICE_NAME"
          write-output "az apim create --name $APIM_SERVICE_NAME --publisher-email `"sheintze@hotmail.com`" --publisher-name `"WaveCentric`" --resource-group $env:$RG --location $env:LOC --public-network-access `"true`" --sku-name `"Consumption`""
          az apim create --name $APIM_SERVICE_NAME --publisher-email "sheintze@hotmail.com" --publisher-name "WaveCentric" --resource-group $env:$RG --location $env:LOC --public-network-access "true" --sku-name "Consumption"
          write-output "az apim api create --service-name $APIM_SERVICE_NAME -g $env:RG --api-id $API_ID --path `"jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs`" --display-name `"$API_ID DisplayName`" --description `"$API_ID Description`" --subscription-required false --api-type `"http`""
          az apim api create --service-name $APIM_SERVICE_NAME -g $env:RG --api-id $API_ID --path "jac3sukjdrxzi-func-CrewTaskMgrAuthSvcs" --display-name "$API_ID DisplayName" --description "$API_ID Description" --subscription-required false --api-type "http" 
          $token=$(az account get-access-token --query 'accessToken' -o tsv)
          $uri = "https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$env:RG/providers/Microsoft.Web/sites/$env:FUNCTIONAPP/host/default/listKeys?api-version=2018-11-01"
          $functionkeylist = az rest --headers "Authorization=Bearer $token" --method post --uri $uri
          $keylistobject = $functionkeylist | ConvertFrom-Json
          $functionKey = $keylistobject.functionKeys.default
          Write-Output "First 5 characters of function key: "
          Write-Output $functionKey.Substring(0,5)
          $ops = az rest --headers "Authorization=Bearer $token" --method get --uri "https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$env:RG/providers/Microsoft.Web/sites/$env:FUNCTIONAPP/functions?api-version=2015-08-01" | jq  .value[].properties.name | tr -d '\r' | tr  '\n' ' ' | tr -d '"' | sed -e 's/\s*/ /'
          foreach ($op in $ops) {
            $op = $op -replace '\s',''
            if($op){
              Write-Host "begin create op=$op"
            }
          }
        azPSVersion: "latest"
